### ISSUE TITLE
建议 、插件优化

### ISSUE THREAD

**Issue by spring1016** [pspgbhu/vue-swipe-mobile#10]
你好，某些原因，借鉴了你的代码，发现一个问题，就是autoplayTime设置之后，如果页面跳转，你这没有清除定时autoplayTimer，导致页面报错，希望作者可以在swpie组件销毁的时候清除一下，避免插件报错

**Comment by pspgbhu** [comment]
@spring1016 非常感谢，之前确实没有考虑到这种情况。我马上会修复的。😊

**Comment by pspgbhu** [comment]
Fixed in commit: 38a40ce
