### ISSUE TITLE
不兼容iphoneX

### ISSUE THREAD

**Issue by 973257307** [pspgbhu/vue-swipe-mobile#13]
在IphoneX的WKWebView里面报错。

**Comment by pspgbhu** [comment]
@973257307  可否把报错的信息提供一下呢？

**Comment by 973257307** [comment]
在iphonex上面引入页面就不显示了，但是把他移除了就好了，具体不知道是什么错，没有调试。

**Comment by pspgbhu** [comment]
应该是 vue 报错了，这个和 wkwebview 没有什么关系。
@973257307 你要不把你写的代码粘一下我看看，越详细越好。

**Comment by pspgbhu** [comment]
@973257307  没有更详细的报错信息，我这里也没法定位问题。那我就暂时先关闭这个 issue 了，如果到时候你有相关错误信息的话，随时欢迎你重新开启这个 issue
