### ISSUE TITLE
图片数量小于等于2个时容易出现bug

### ISSUE THREAD

**Issue by zangse** [pspgbhu/vue-swipe-mobile#6]
当图片为1张时，滑动后很容易卡住在两个图片之间
当图片为2张时，右滑正常，左滑很容易滚回去
因为项目的原因，图片数量在1~3张之间，也有可能是我打开的姿势不对

**Comment by pspgbhu** [comment]
@zangse 当初设计的时候确实没太考虑只有一两张图片的情况，今天我找时间定位一下问题，争取今天能修复已知问题。

**Comment by pspgbhu** [comment]
@zangse c-swipe 最新版已经修复了这些问题。你可以运行 `npm install c-swipe@2.0.2` 安装最新版的 `c-swipe`

**Comment by zangse** [comment]
@pspgbhu 已更新，没问题，可以的，老铁
