### ISSUE TITLE
二维码是个什么梗???

### ISSUE THREAD

**Issue by jessie-zly** [pspgbhu/vue-swipe-mobile#8]
我只是想扫个二维码看看什么情况,结果来了个404,僵硬...

系统:
- iphone6

- 11.2.5

**Comment by pspgbhu** [comment]
还好你提醒我了。 预览链接之前改过，但是二维码忘记更换了。

README 里的二维码刚刚更换完毕了。或者直接扫这个也可以。

<img width="95" alt="c-swipe" src="https://user-images.githubusercontent.com/18444796/36627887-915f74cc-1984-11e8-969d-7905298e0015.png">
